# QQBot、QQ频道的过审模式、启用后非白名单群、频道只会响应白名单内的功能
# 默认配置
default:
  #只启用功能，配置后只有该功能才响应
  enable:

    #禁用功能，功能名称,例如：十连、角色查询、体力查询、用户绑定、抽卡记录、添加表情、欢迎新人、退群通知
  #禁用功能，功能名称,例如：云崽帮助、角色素材、今日素材、养成计算、米游社公告
  disable:
    - 禁用示例
    - 支持多个

# 单独appid设置
12345:
  #只启用功能，配置后只有该功能才响应
  enable:

  #禁用功能，功能名称,例如：十连、角色查询、体力查询、用户绑定、抽卡记录、添加表情、欢迎新人、退群通知
  #禁用功能，功能名称,例如：云崽帮助、角色素材、今日素材、养成计算、米游社公告
  disable:
    - 禁用示例
    - 支持多个
